from __future__ import annotations

from dataclasses import dataclass
from typing import Dict, Optional


@dataclass
class GenerationOptions:
    language: str = "python"
    max_lines: int = 200


class CodeGenerator:
    """Lightweight, provider-agnostic code generator.

    Notes:
    - Default provider is 'local' which uses deterministic templates (no external deps)
    - When settings.enable_code_generation and provider == 'ollama', a separate
      integration can be added later. This local version is SAFE and deterministic.
    """

    def __init__(self, provider: str = "local", model: Optional[str] = None) -> None:
        self.provider = provider
        self.model = model or "codellama:7b"

    def generate_code(self, spec: str, options: Optional[GenerationOptions] = None) -> Dict[str, str]:
        options = options or GenerationOptions()
        lang = options.language.lower()
        if self.provider != "local":
            # Fallback to local deterministic templates for safety
            self.provider = "local"

        if lang == "python":
            body = self._python_template(spec)
        elif lang in {"typescript", "ts"}:
            body = self._typescript_template(spec)
        else:
            body = self._generic_template(spec)

        # Trim to max_lines
        lines = body.splitlines()
        body = "\n".join(lines[: options.max_lines])
        return {"language": lang, "code": body}

    # --- Templates ---
    def _python_template(self, spec: str) -> str:
        lines = [
            "# Generated by CodeGenerator (local template)",
            f"# Spec: {spec}",
            "",
            "from typing import Any",
            "",
            "def main(input_data: Any) -> Any:",
            '    """TODO: implement logic for the provided spec."""',
            "    # NOTE: This is a safe skeleton; fill in real logic as needed.",
            '    raise NotImplementedError("Implement main() according to spec")',
        ]
        return "\n".join(lines)

    def _typescript_template(self, spec: str) -> str:
        lines = [
            "// Generated by CodeGenerator (local template)",
            f"// Spec: {spec}",
            "",
            "export function main(input: unknown): unknown {",
            "  // TODO: implement logic for the provided spec",
            "  throw new Error('NotImplemented');",
            "}",
        ]
        return "\n".join(lines)

    def _generic_template(self, spec: str) -> str:
        lines = [
            "// Generated by CodeGenerator (local template)",
            f"// Spec: {spec}",
            "",
            "// TODO: implement according to the spec",
        ]
        return "\n".join(lines)

