from __future__ import annotations

from typing import Dict


class DocGenerator:
    """Simple documentation generator that creates a README-style summary."""

    def generate_docs(self, title: str, description: str) -> Dict[str, str]:
        md = (
            f"# {title}\n\n"
            f"## Summary\n\n{description}\n\n"
            "## How it works\n\n"
            "This document was generated by a deterministic template. Replace this section with implementation details, examples, and API docs.\n"
        )
        return {"language": "markdown", "content": md}

